# -*- mode: ruby -*-
# vi: set ft=ruby:

# Vagrant script for a multi-guest VirtualBox SDN lab with Ryu/nmeta

#*** Vagrant Configuration for Guest Parameters:

## Vagrant config
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #*** Switch 1 (sw1):
  config.vm.define "sw1" do |sw1|
    #*** Define box and hostname:
    sw1.vm.box = "bento/ubuntu-16.04"
    sw1.vm.hostname = "sw1"

    #*** Initial network interface configuration:
    sw1.vm.network "private_network", auto_config: false, virtualbox__intnet: "Switch1-Client1"
    sw1.vm.network "private_network", auto_config: false, virtualbox__intnet: "Switch1-Switch2"
    sw1.vm.network "private_network", auto_config: false, virtualbox__intnet: "Foo"
    sw1.vm.network "private_network", ip: "172.16.0.5", netmask: "255.255.252.0", virtualbox__intnet: "TestControl"
    sw1.vm.network "private_network", auto_config: false, virtualbox__intnet: "Switch1-LoadGen1"

    #*** Virtualbox-specific settings:
    sw1.vm.provider :virtualbox do |vb|
      #*** Set number of CPUs:
      vb.cpus = "1"
      #*** Set RAM:
      vb.customize ["modifyvm", :id, "--memory", "512"]
      #*** Run non-headless:
      vb.gui = true
      #*** Enable promiscuous mode on the switch interfaces:
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc6", "allow-all"]
    end
    #*** Run provision scripts:
    sw1.vm.provision :shell, path: "bootstrap_swX.sh", privileged: false
    sw1.vm.provision :shell, path: "bootstrap_sw1.sh", privileged: false
  end

  #*** Switch 2 (sw2):
  config.vm.define "sw2" do |sw2|
    #*** Define box and hostname:
    sw2.vm.box = "bento/ubuntu-16.04"
    sw2.vm.hostname = "sw2"

    #*** Initial network interface configuration:
    sw2.vm.network "private_network", auto_config: false, virtualbox__intnet: "Switch2-Server1"
    sw2.vm.network "private_network", auto_config: false, virtualbox__intnet: "Switch1-Switch2"
    sw2.vm.network "private_network", auto_config: false, virtualbox__intnet: "Foo"
    sw2.vm.network "private_network", ip: "172.16.0.9", netmask: "255.255.252.0", virtualbox__intnet: "TestControl"
    sw2.vm.network "private_network", auto_config: false, virtualbox__intnet: "Switch2-LoadReflector1"

    #*** Virtualbox-specific settings:
    sw2.vm.provider :virtualbox do |vb|
      #*** Set number of CPUs:
      vb.cpus = "1"
      #*** Set RAM:
      vb.customize ["modifyvm", :id, "--memory", "512"]
      #*** Run non-headless:
      vb.gui = true
      #*** Enable promiscuous mode on the switch interfaces:
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc6", "allow-all"]
    end
    #*** Run provision scripts:
    sw2.vm.provision :shell, path: "bootstrap_swX.sh", privileged: false
    sw2.vm.provision :shell, path: "bootstrap_sw2.sh", privileged: false
  end

  #*** Client (pc1):
  config.vm.define "pc1" do |pc1|
    #*** Define box and hostname:
    pc1.vm.box = "bento/ubuntu-16.04"
    pc1.vm.hostname = "pc1"

    #*** Initial network interface configuration:
    pc1.vm.network "private_network", ip: "10.1.0.1", netmask: "255.255.252.0", virtualbox__intnet: "Switch1-Client1"
    pc1.vm.network "private_network", ip: "172.16.0.1", netmask: "255.255.252.0", virtualbox__intnet: "TestControl"

    #*** Virtualbox-specific settings:
    pc1.vm.provider :virtualbox do |vb|
      #*** Set number of CPUs:
      vb.cpus = "1"
      #*** Set RAM:
      vb.customize ["modifyvm", :id, "--memory", "512"]
      #*** Run non-headless:
      vb.gui = true
    end
    #*** Run provision script:
    pc1.vm.provision :shell, path: "bootstrap_pc1.sh", privileged: false
  end

  #*** Server (sv1):
  config.vm.define "sv1" do |sv1|
    #*** Define box and hostname:
    sv1.vm.box = "bento/ubuntu-16.04"
    sv1.vm.hostname = "sv1"

    #*** Initial network interface configuration:
    sv1.vm.network "private_network", ip: "10.1.0.2", netmask: "255.255.252.0", virtualbox__intnet: "Switch2-Server1"
    sv1.vm.network "private_network", ip: "172.16.0.2", netmask: "255.255.252.0", virtualbox__intnet: "TestControl"

    #*** Virtualbox-specific settings:
    sv1.vm.provider :virtualbox do |vb|
      #*** Set number of CPUs:
      vb.cpus = "1"
      #*** Set RAM:
      vb.customize ["modifyvm", :id, "--memory", "512"]
      #*** Run non-headless:
      vb.gui = true
    end
    #*** Run provision script:
    sv1.vm.provision :shell, path: "bootstrap_sv1.sh", privileged: false
  end

  #*** Controller (ct1):
  config.vm.define "ct1" do |ct1|
    #*** Select box (uncomment either bento server or boxcutter desktop):
    #ct1.vm.box = "boxcutter/ubuntu1604-desktop"
    ct1.vm.box = "bento/ubuntu-16.04"
    
    #*** Set hostname:
    ct1.vm.hostname = "ct1"

    #*** Initial network interface configuration:
    ct1.vm.network "private_network", ip: "172.16.0.3", netmask: "255.255.252.0", virtualbox__intnet: "TestControl"

    #*** Virtualbox-specific settings:
    ct1.vm.provider :virtualbox do |vb|
      #*** Set number of CPUs:
      vb.cpus = "2"
      #*** Set RAM:
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      #*** Run non-headless:
      vb.gui = true
    end
    #*** Run provision script as unprivileged user 'vagrant':
    ct1.vm.provision :shell, path: "bootstrap_ct1.sh", privileged: false
  end
end

